export enum Discounts {
  NO_DISCOUNT = 0,
  TEN_PERCENT_DISCOUNT = 0.1,
  TWENTY_PERCENT_DISCOUNT = 0.2,
  THIRTY_PERCENT_DISCOUNT = 0.3,
  FORTY_PERCENT_DISCOUNT = 0.4,
  FIFTY_PERCENT_DISCOUNT = 0.5,
}
